### ISSUE TITLE
yarn install fail

### ISSUE THREAD

**Issue by yilongdong** [yuzheng14/ubuntu-frontend-setup#1]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/62591650/221906872-91a2f7f8-7d31-466d-950e-ae25c7e5454e.png">

**Comment by yuzheng14** [comment]
最后有个提示 `======== 安装完成，请重启 shell 以应用 zsh 及其他改动 ========` 哦

如果不方便重启可以手动键入 `zsh` 指令进入 zsh

**Comment by yilongdong** [comment]
好的，谢谢
